databases:
  - name: learning_log_db
    plan: free

services:
  - type: web
    name: learning-log-service
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn learning_log.wsgi:application"

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: learning_log_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "3"
